config/routes.rb
Mandiantex::Application.routes.draw do
  resources :search_suggestions

  resources :media_items, :only => [:show, :index]
  

end

app/models/media_item.rb
# == Schema Information
#
# Table name: media_items
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  author       :string(255)
#  publisher    :string(255)
#  published_on :string(255)
#  unit_cost    :integer
#  category     :string(255)
#  currency     :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

require 'csv'
require 'iconv'

class MediaItem < ActiveRecord::Base
  attr_accessible :author, :category, :currency, :published_on, :publisher, :title, :unit_cost, :price
  
  include Tire::Model::Search
  include Tire::Model::Callbacks  
  index_name INDEX_NAME

  MARKUP = YAML.load_file("#{Rails.root}/config/markup.yml")
  CSV_FILE = File.join( Rails.root.to_s, 'db', "import", "media_items.csv")
  
  composed_of :unit_cost,
              :class_name => 'Money',
              :mapping => [%w(unit_cost fractional), %w(currency currency_as_string)],
              :constructor => Proc.new { |unit_cost, currency| Money.new(unit_cost, currency || Money.default_currency) },
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? (value.to_f.to_money rescue Money.empty) : Money.empty }
  
  validates :title, :presence => {:message => 'cannot be blank'}
  validates :author, :presence => {:message => 'cannot be blank'}
  validates :publisher, :presence => {:message => 'cannot be blank'}
  validates :category, :presence => {:message => 'cannot be blank'}
  validates :published_on, :presence => true
  
  
  mapping do
    indexes :id, :index => :not_analyzed
    indexes :currency, :index => :not_analyzed
    indexes :unit_cost, :index => :not_analyzed
    indexes :published_on, :index => :not_analyzed
    indexes :title, :type => 'multi_field', :fields => { :title =>  { :type => 'string', :analyzer => 'snowball' },
                                                         :exact => { :type => 'string', :index => 'not_analyzed' } }
    indexes :author, :type => 'multi_field', :fields => { :author =>  { :type => 'string', :analyzer => 'snowball' },
                                                        :exact => { :type => 'string', :index => 'not_analyzed' } }
    indexes :price, :type => 'multi_field', :fields => { :price =>  { :type => 'float', :analyzer => 'keyword' },
                                                        :exact => { :type => 'float', :index => 'not_analyzed' } }
    indexes :category, :analyzer => 'keyword'
    indexes :publisher, :analyzer => 'snowball'
  end  
  
  def self.search(params)
    tire.search(load: true, page: params[:page], per_page: 10) do
      if params[:query].present?
        query { string params[:query], default_operator: "AND" }
      else
        query { all }
      end
      
      sort { by "title.exact", params[:sort][:title]} if params[:sort].present? && !params[:sort][:title].blank?
      sort { by "author.exact", params[:sort][:author]} if params[:sort].present? && !params[:sort][:author].blank?
      sort { by "price.exact", params[:sort][:price]} if params[:sort].present? && !params[:sort][:price].blank?
    end
  end
  
  
  def price
    unit_cost.to_d * ( 1 + MARKUP[self.category] )
  end
  
  def display_price
    price.to_s
  end
  
  def to_indexed_json
    to_json(methods: [:display_price, :price])
  end
  
  def self.import_csv
    begin
      CSV.foreach(MediaItem::CSV_FILE, {:headers => true, :header_converters => :symbol}) do |row|
        media_item = MediaItem.find_by_title_and_author_and_publisher_and_published_on(row[:title], row[:author], row[:publisher], row[:published_on]) || MediaItem.new
        media_item.attributes = row.to_hash.merge({:currency => "USD"})
        media_item.unit_cost = row[:unit_cost].to_f * 100.0
        media_item.save!
      end
    rescue Exception => e
      puts e.message
      puts "Media item could not be created for row: #{row.to_hash}" if row
    end
  end
end

app/controllers/media_items_controller.rb
require 'will_paginate/array'

class MediaItemsController < ApplicationController
  # GET /media_items
  # GET /media_items.json
  def index
    params[:search] = {} unless params[:search]
    init_search_sort
    @media_items = MediaItem.search(params[:search].merge({:page => params[:page] || 1, :per_page => 10}))
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @media_items }
    end
  end

  # GET /media_items/1
  # GET /media_items/1.json
  def show
    @media_item = MediaItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @media_item }
    end
  end

  # # GET /media_items/new
  # # GET /media_items/new.json
  # def new
  #   @media_item = MediaItem.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @media_item }
  #   end
  # end
  # 
  # # GET /media_items/1/edit
  # def edit
  #   @media_item = MediaItem.find(params[:id])
  # end
  # 
  # # POST /media_items
  # # POST /media_items.json
  # def create
  #   @media_item = MediaItem.new(params[:media_item])
  # 
  #   respond_to do |format|
  #     if @media_item.save
  #       format.html { redirect_to @media_item, notice: 'Media item was successfully created.' }
  #       format.json { render json: @media_item, status: :created, location: @media_item }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @media_item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # PUT /media_items/1
  # # PUT /media_items/1.json
  # def update
  #   @media_item = MediaItem.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @media_item.update_attributes(params[:media_item])
  #       format.html { redirect_to @media_item, notice: 'Media item was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @media_item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # DELETE /media_items/1
  # # DELETE /media_items/1.json
  # def destroy
  #   @media_item = MediaItem.find(params[:id])
  #   @media_item.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to media_items_url }
  #     format.json { head :no_content }
  #   end
  # end
  
  private
  
  def init_search_sort
    if params[:sort].to_s.start_with?("title")
      title_direction = params[:sort].to_s.split("!").first
      title_direction.slice!("title_")
      params[:search][:sort] = {}
      params[:search][:sort][:title] = title_direction
    end
    if params[:sort].to_s.start_with?("author")
      author_direction = params[:sort].to_s.split("!").first
      author_direction.slice!("author_")
      params[:search][:sort] = {}
      params[:search][:sort][:author] = author_direction
    end
    if params[:sort].to_s.start_with?("unit_cost")
      price_direction = params[:sort].to_s.split("!").first
      price_direction.slice!("unit_cost_")
      params[:search][:sort] = {}
      params[:search][:sort][:price] = price_direction
    end
  end
  
  # def price_sort
  #   if params[:sort].to_s.start_with?("unit_cost")
  #     unit_cost_direction = params[:sort].to_s.split("!").first
  #     unit_cost_direction.slice!("unit_cost_")
  #     @media_items = price_direction_sort(unit_cost_direction)
  #   end
  # end
  # 
  # def price_direction_sort(direction)
  #   @media_items = direction.eql?("asc") ? @media_items.sort{|a,b|a.price<=>b.price} : @media_items.sort{|a,b|a.price<=>b.price}.reverse!
  #   @media_items = @media_items.paginate(:page => params[:page], :per_page => 10)
  # end
end

app/helpers/media_items_helper.rb
module MediaItemsHelper
end

app/views/media_items/_form.html.erb
<%= form_for(@media_item) do |f| %>
  <% if @media_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media_item.errors.count, "error") %> prohibited this media_item from being saved:</h2>

      <ul>
      <% @media_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.text_field :published_on %>
  </div>
  <div class="field">
    <%= f.label :unit_cost %><br />
    <%= f.text_field :unit_cost, :value => @media_item.unit_cost %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media_items/edit.html.erb
<h1>Editing media_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @media_item %> |
<%= link_to 'Back', media_items_path %>

app/views/media_items/index.html.erb
<h1>Listing</h1>

<%= form_tag media_items_path, method: :get do %>
  <p>
    <%= text_field_tag "search[query]", params[:search][:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<p><%= will_paginate @media_items %></p>
<table id="table" class="parse">
  <tr>
    <th></th>
    <th><%= link_to_sorted "Title", :title %></th>
    <th><%= link_to_sorted "Author", :author %></th>
    <th><%= link_to_sorted "Price", :unit_cost %></th>
  </tr>

<% @media_items.each do |media_item| %>
  <tr class="tablerow" data-url="<%= media_item_path(media_item) %>">
    <td><%= link_to 'Show', media_item %></td>
    <td><%= media_item.title %></td>
    <td><%= media_item.author %></td>
    <td><%= Money.new(media_item.price).exchange_to(@currency).format %></td>
  </tr>
<% end %>
</table>

app/views/media_items/new.html.erb
<h1>New media_item</h1>

<%= render 'form' %>

<%= link_to 'Back', media_items_path %>

app/views/media_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @media_item.title %>
</p>

<p>
  <b>Author:</b>
  <%= @media_item.author %>
</p>

<p>
  <b>Publisher:</b>
  <%= @media_item.publisher %>
</p>

<p>
  <b>Category:</b>
  <%= @media_item.category %>
</p>

<p>
  <b>Published on:</b>
  <%= @media_item.published_on %>
</p>

<p>
  <b>Unit cost:</b>
  <%= Money.new(@media_item.unit_cost).exchange_to(@currency).format %>
</p>

<p>
  <b>Price:</b>
  <%= Money.new(@media_item.price).exchange_to(@currency).format %>
</p>


<%= link_to 'Back', media_items_path %>